import * as Accordion from '@radix-ui/react-accordion';
import { ChevronDown } from 'lucide-react';

export default function FAQ() {
  const faqs = [
    {
      q: 'Is Geleya completely free?',
      a: 'Yes — Geleya is 100% free for all students. No subscription, no credit card, no hidden fees. Ever.',
    },
    {
      q: 'Is my journal entry kept private?',
      a: 'Absolutely. Your entries are encrypted and never shared with anyone — not your college, not your parents, not advertisers.',
    },
    {
      q: 'What is the AI Stress Score?',
      a: "It's a 0–10 score generated by our Neural Network + Sentiment Analysis that reads your journal entry and tells you exactly how stressed you are, and why.",
    },
    {
      q: 'Does Geleya replace a therapist?',
      a: "No — Geleya is a supportive tool, not a replacement for professional care. If your stress is critical, Geleya will always connect you to real human help.",
    },
    {
      q: 'Can my college deploy Geleya campus-wide?',
      a: 'Yes! We partner with institutions to deploy Geleya for all students at no cost to them. Contact us to learn more.',
    },
    {
      q: 'What AI model powers Geleya?',
      a: "Geleya is powered by Gemma 4 — Google's open-source AI model — combined with our own Neural Network stress classifier.",
    },
  ];

  return (
    <div className="max-w-3xl mx-auto px-8 py-24">
      <h2
        className="text-3xl md:text-4xl text-black text-center"
        style={{ fontFamily: "'Instrument Serif', serif" }}
      >
        Questions? We've got answers.
      </h2>

      <Accordion.Root type="single" defaultValue="item-0" collapsible className="mt-12 space-y-4">
        {faqs.map((faq, index) => (
          <Accordion.Item
            key={index}
            value={`item-${index}`}
            className="rounded-xl border border-gray-100 px-6 py-5 bg-white"
          >
            <Accordion.Trigger className="flex w-full items-center justify-between text-left group">
              <span className="font-semibold text-sm text-black">{faq.q}</span>
              <ChevronDown className="w-5 h-5 text-[#6F6F6F] transition-transform group-data-[state=open]:rotate-180" />
            </Accordion.Trigger>
            <Accordion.Content className="overflow-hidden data-[state=open]:animate-slideDown data-[state=closed]:animate-slideUp">
              <div className="text-sm text-[#6F6F6F] mt-2 leading-relaxed">{faq.a}</div>
            </Accordion.Content>
          </Accordion.Item>
        ))}
      </Accordion.Root>
    </div>
  );
}
